name: Hello Ehab
repo: https://github.com/troykinsella/concourse-ansible-playbook-resource
container_image: troykinsella/concourse-ansible-playbook-resource
description: |
  I have regenerated a permanent GH_TOKEN
