name: I Love you Yasminty <3
repo: https://github.com/troykinsella/concourse-ansible-playbook-resource
container_image: troykinsella/concourse-ansible-playbook-resource
description: |
  I generated a permanent GH_TOKEN
